### ISSUE TITLE
Not working with 11.0.2

### ISSUE THREAD

**Issue by Flanell88** [Beast-Masters-addons/pet-battle-teams#1]
The addon isnt working anymore with TWW 11.0.2 release. Can you please update it?

**Comment by datagutten** [comment]
I tried to fix it and released a new alpha build now: https://addons.wago.io/addons/j6jzyM6R
Basic team switching seems to work, but I have not tested all functions yet.

**Comment by Kickbanblock** [comment]
Still not working for me. :(

**Comment by datagutten** [comment]
I fixed the "Mend Pets" button and the right-click menus and released stable version 3.6. If you still have problems, please tell me if you get any Lua errors.

**Comment by Kickbanblock** [comment]
It works now! Thank you so much, it would have been terrible to play the start of the next expansion without this addon. :D
